INSERT INTO `Product` (category_id, name, price, image) VALUES
(1, 'Crispy Onion Rings', 6, 'Crispy-Onion-Rings.png'),
(1, 'Ancho Chili Cheese Quesadilla', 6, 'Ancho-Chili-Cheese-Quesadilla.png'),
(1, 'Thai Spring Rolls', 7, 'Thai-Spring-Rolls.png'),
(2, 'Cream of Wild Mushroom', 4, 'Cream-of-Wild-Mushroom.png'),
(2, 'Tasty Chicken Noodle soup', 4, 'Tasty-Chicken-Noodle-soup.png'),
(3, 'Classic Caesar Salad', 7, 'Classic-Caesar-Salad.png'),
(3, 'Cranberry Pecan Blue', 8, 'Cranberry-Pecan-Blue.png'),
(3, 'Spinach Salad', 9, 'Spinach-Salad.png'),
(4, 'House Roasted Turkey Club', 9, 'House-Roasted-Turkey-Club.png'),
(4, 'Hot Italian Grinder', 9, 'Hot-Italian-Grinder.png'),
(4, 'The BLT+AA', 7, 'The-BLT+AA.png'),
(5, 'Classic Hamburger', 10, 'Classic-Hamburger.png'),
(5, 'Classic Cheeseburger', 11, 'Classic-Cheeseburger.png'),
(5, 'The "Works" Burger', 12, 'The-Works-Burger.png'),
(6, 'Beer Battered Fish and Chips', 14, 'Beer-Battered-Fish-and-Chips.png'),
(6, 'Barbecued Short Rib', 12, 'Barbecued-Short-Rib.png'),
(6, 'Herb Crusted Atlantic Salmon', 18, 'Herb-Crusted-Atlantic-Salmon.png'),
(7, 'French Fries', 3, 'French-Fries.png'),
(7, 'Corn on the Cobb', 3, 'Corn-on-the-Cobb.png'),
(7, 'Baked Beans', 3, 'Baked-Beans.png'),
(8, 'Our Homemade Lemonade', 8, 'Our-Homemade-Lemonade.png'),
(8, 'Our Homemade Iced Tea', 8, 'Our-Homemade-Iced-Tea.png'),
(8, 'Lungo', 7, 'Lungo.png'),
(8, 'Espresso', 7, 'Espresso.png'),
(8, 'Espresso con panna', 9, 'Espresso-con-panna.png'),
(8, 'Espressino', 9, 'Espressino.png'),
(8, 'Latte', 9, 'Latte.png'),
(8, 'Cappuccino', 9, 'Cappuccino.png'),
(8, 'Grapefruit Juice', 9, 'Grapefruit-Juice.png'),
(8, 'Grape Juice', 9, 'Grape-Juice.png'),
(8, 'Sodas', 9, 'Sodas-can.jpg'),
(8, 'Orange Juice', 9, 'orange-juice.jpg'),
(8, 'Lemonado', 9, 'lemonado.jpg'),
(9, 'Dutch Apple Pie', 5, 'Dutch-Apple-Pie.png'),
(9, 'German Chocolate Cake', 5, 'German-Chocolate-Cake.png'),
(9, 'Key Lime Pie', 5, 'Key-Lime-Pie.png';
